daphne-eu/daphne

build.sh
In GitLab by @psomas on Mar 31, 2022, 10:50
antlr4-4.9.2 uses the unauthenticated git:// protocol to clone a Github repo for a dependency. Unauthenticated git:// isn't supported by Github anymore. This leads to an antlr4 (and subsequently daphne) build failure. Patch antlr4 to use https:// until we upgrade to antlr4-4.9.3+, which has switched to https://.
Closes #216
=> [DAPHNE-#216] ANTLR not found while building

src/runtime/local/vectorized/LoadPartitioning.h
This fixes [issue #340](https://github.com/daphne-eu/daphne/issues/340).
This fixes the calculation of the chunk size for FISS and VISS scheduling. The actual_step variable was being recasted inside the while loop and getStages always returned 1.
=> [DAPHNE-340] Fix FISS chunk size calculation

src/runtime/local/kernels/ColBind.h, src/runtime/local/kernels/kernels.json, test/runtime/local/kernels/ColBindTest.cpp
- Implements column binding for CSRMatrix datatype.
- Closes #218.
=> [DAPHNE-#218]: colBind-kernel for CSRMatrix

src/runtime/local/kernels/Reshape.h, test/runtime/local/kernels/ReshapeTest.cpp
- Implements reshape-kernel for views on `DenseMatrix` datatype.
- Closes #224.
=> [DAPHNE-#224]: reshape-kernel for non-zero-copy cases

src/ir/daphneir/DaphneInferSparsityOpInterface.cpp, src/ir/daphneir/DaphneOps.td, src/runtime/local/kernels/DiagMatrix.h, src/runtime/local/kernels/kernels.json, test/CMakeLists.txt, test/runtime/local/kernels/DiagMatrixTest.cpp
- Add CSR specializations for the diagMatrix kernel.
- Add sparsity inference for the diagMatrix() daphne op.
Closes https://github.com/daphne-eu/daphne/issues/31
=> [DAPHNE-#31] Kernel for diagMatrix-operation

src/ir/daphneir/DaphneInferShapeOpInterface.cpp
Fixed a bug where inferNumColsFromArgs would use rows instead of columns.
=> [DAPHNE-#350]: DaphneDSL: rbind checks number of rows instead the number of columns

src/runtime/local/kernels/AggAll.h, src/runtime/local/kernels/AggRow.h, src/runtime/local/kernels/kernels.json, test/runtime/local/kernels/AggAllTest.cpp, test/runtime/local/kernels/AggRowTest.cpp
- Support for Aggregate-All `mean` for Dense and CSR matrices.
- Support for Aggregate-Row `mean` for Dense and CSR matrices.
- Some testcases.
Closes #393.
=> Support for mean operation for all-aggregation and row-aggregation.

src/ir/daphneir/DaphneOps.td, src/parser/daphnedsl/CMakeLists.txt, src/parser/daphnedsl/DaphneDSLGrammar.g4, src/parser/daphnedsl/DaphneDSLVisitor.cpp, src/parser/daphnedsl/DaphneDSLVisitor.h, src/runtime/local/datastructures/DenseMatrix.cpp, src/runtime/local/datastructures/ValueTypeUtils.cpp, src/runtime/local/datastructures/ValueTypeUtils.h, src/runtime/local/kernels/MatrixConstant.h, src/runtime/local/kernels/kernels.json, test/CMakeLists.txt, test/api/cli/expressions/MatrixLiteralTest.cpp, test/api/cli/expressions/matrix_literal_failure_1.daphne, test/api/cli/expressions/matrix_literal_success_1.daphne, test/api/cli/expressions/matrix_literal_success_1.txt, test/tags.h
Implements Matrix literal for DaphneDSL.
- A light `bool` type support for `DenseMatrix` is added (for print and reshape kernels).
- Creates a `DenseMatrix` with shape (nx1) of type `int64_t`,  `double` or `bool` inside `DaphneDSLVisitor`.
- Usage example: `x = [1, 2, 3]` or `x = [1.1, 2.2, 3.3]` or `x = [true, false, true]`.
- Throws error in case of:
- - You try to create a matrix with mixed types (e.g., `x = [1, 2.2, 3]`).
- - You try to create an empty matrix: can't infer the type.
- - You use a not yet defined in `ValueTypeUtils` type (e.g., `const char*`).
Closes #358 .
=> [DAPHNE-#358]: DaphneDSL: Matrix literals

src/runtime/local/kernels/CTable.h, src/runtime/local/kernels/kernels.json, test/CMakeLists.txt, test/runtime/local/kernels/CTableTest.cpp
Implements kernel for contingency table (`ctable`) operation.
- Implements kernel for `DenseMatrix` inputs and `DenseMatrix` output.
- Implements kernel for `DenseMatrix` inputs and `CSRMatrix` output.
Closes #390.
=>  [DAPHNE-#390]: Kernel for ctable operation

src/runtime/local/kernels/Group.h, src/runtime/local/kernels/Order.h, src/runtime/local/kernels/kernels.json, test/CMakeLists.txt, test/api/cli/sql/SQLTest.cpp, test/runtime/local/kernels/GroupTest.cpp
* Implements column-wise group aggregation on Frames
* Supports the aggregation functions count, sum, min, max and average
* Only materialzes an ordered version of the input frame and the result frame
* Reduces the input frame to key and aggregation columns before mutli-column ordering (without copying) for efficieny
* Utilizes the Order & extractCol Kernel, as well as the  DeduceType Util
* Refactors the Order Kernel to use the DeduceType Util
* Adds an optional export the group vector from the Order Kernel
* This option is less efficient in the last sort step, but overall increases efficiency in scenarios where the final group vector is reused (e.g. Group Kernel)
* Fixes a Warning in ExtractCol (redundant comparison)
* closes https://github.com/daphne-eu/daphne/issues/242
=> Draft: [DAPHNE-#242] Kernel for GroupOp on Frame

src/runtime/local/datagen/GenGivenVals.h, src/runtime/local/datastructures/DenseMatrix.cpp, src/runtime/local/datastructures/DenseMatrix.h, src/runtime/local/datastructures/ValueTypeUtils.cpp, test/runtime/local/datastructures/DenseMatrixTest.cpp
- Implements `DenseMatrix` template specification for `const char*`.
- Additional argument `strBufCapacity` is introduced to allow user-defined initial strings buffer capacity.
- A small `CharBuf` struct is introduced and used for storing and managing `char *` buffer of **null-terminated** strings.
- `DenseMatrix` for strings is built around two arrays:
- - `strings` - Character array stored in `CharBuf`.
- - `values` - A `DenseMatrix` local array with `const char *` offsets in `strings`.
- `DenseMatrix` constructor sets all strings to `\0` by default to avoid issues regarding null-termination.
- Supports `set()`: memory in `strings` is shifted and `values` are adjusted according to `diff` between strings.
- Supports `append()`: any previous content gets simply overwritten.
- Supports …
=> [DAPHNE-#230]:  String as value type of DenseMatrix

src/runtime/local/kernels/Order.h, src/runtime/local/kernels/kernels.json, test/runtime/local/kernels/OrderTest.cpp
* Implements specialization of the order-kernel for DenseMatrix
* Works in the single column and multi-column case
* Slight changes to existing order methods to respect the rowSkip in multi-column matrices
* Builds on the Order Kernel DeduceType Util Refactor from #242
* closes #388
=> [DAPHNE-#388] order-kernel for DenseMatrix

src/ir/daphneir/DaphneInferShapeOpInterface.cpp, src/ir/daphneir/DaphneOps.td, src/parser/daphnedsl/DaphneDSLBuiltins.cpp, src/runtime/local/kernels/Order.h, src/runtime/local/kernels/kernels.json, test/runtime/local/kernels/OrderTest.cpp
* implements returning the index matrix from the OrderOp if a boolean flag is set
* shape inference adaptation (to include the case mentioned above)
* builds on #388
=> [DAPHNE-#389] order-kernel: return indexes instead of ordered data object

src/parser/ParserUtils.h, src/parser/daphnedsl/DaphneDSLVisitor.cpp, src/parser/sql/SQLVisitor.cpp
ANTLR version 4.9.3 raised an issue with both parsers (daphne and sql).
Both had instances where antlrcpp::Any was implicitly cast to another type, like mlir::Value and mlir::Type.
This should close Issue #420
=> [DAPHNE-#420]: ANTLR Any Conversion.

CONTRIBUTING.md, doc/README.md, doc/development/HandlingPRs.md
- This initial draft mainly summarizes how we have handled pull requests so far.
- Furthermore, it goes beyond that at some points (e.g., quick initial summary and reviewer selection process).
- The focus is mostly on the overall process of handling a PR.
- Closes #419.
=> [DAPHNE-#419] Guidelines on handling pull requests

src/runtime/local/kernels/Order.h, test/CMakeLists.txt, test/api/cli/sql/SQLResultTest.cpp, test/api/cli/sql/group_1.daphne, test/api/cli/sql/group_1.txt, test/runtime/local/kernels/GroupTest.cpp
* fixed a bug in the order kernels group export
* added group by tests specifically for key columns with no and all distinct values
* closes #417
=> [DAPHNE-#417] Incorrect GROUP BY result when all keys are the same

doc/DistributedRuntime.md, doc/README.md, doc/development/ExtendingDistributedRuntime.md, scripts/examples/distributed.daph
Added two .md files, both related to the use and development of the distributed runtime.
- One documentation file for the Daphne user, how to deploy distributed nodes (workers) and execute a script on the distributed runtime.
- One documentation file for the Daphne developer, explaining the basics on how to extend the existing infrastructure of the distributed runtime.
=> Distributed runtime documentation.

.gitignore, pack.sh, release.sh
This commit adds the --feature parameter to the release scripts which enables packaging a release with a specified feature compiled. This is a workaround for release 0.1 to fix a binary dependency on CUDA libraries.
Closes #452
=> [DAPHNE-#452] Release script feature parameter

.github/workflows/main.yml, CMakeLists.txt, build.sh, doc/DaphneDSLBuiltins.md, doc/GettingStarted.md, doc/README.md, doc/development/BuildingDaphne.md, pack.sh, release.sh, src/parser/config/ConfigParser.cpp, src/runtime/distributed/worker/CMakeLists.txt, src/runtime/local/io/ReadParquet.h, src/runtime/local/kernels/CMakeLists.txt, src/runtime/local/kernels/Read.h, test.sh, test/runtime/local/io/ReadParquetTest.cpp, thirdparty/patches/0004-arrow-git-log.patch
This PR contains several minor and major improvements to our infamous build script. Some of it is prep work for building daphne containers.
Commit messages speak for themselves but here's a quick summary:
* The clean parameters are changed according to #466 
* The prefix where third party dependencies are installed can be set with --installPrefix <path>
* The LLVM/MLIR dependency is now installed into installPrefix and the use of buildPrefix removed from the main cmake config invocation (at the bottom of build.sh)
* Third party dependency compilation can be omitted via --no-deps flag
=> Build script improvements

src/ir/daphneir/DaphneDialect.cpp, test/api/cli/distributed/distributed_1.daphne, test/api/cli/distributed/distributed_2.daphne
Both vectorized and distributed pipelines could include an input multiple times in the pipeline input array.
Updated canonicalization pass for VectorizedPipelineOp in order to scan for duplicate inputs and in case both inputs have the same `VectorSplits` entry, one of them is removed.
Closes #461.
=> Duplicate inputs in pipeline input array.

src/runtime/distributed/coordinator/kernels/Broadcast.h, src/runtime/distributed/coordinator/kernels/Distribute.h, src/runtime/distributed/coordinator/kernels/DistributedCompute.h, src/runtime/distributed/coordinator/scheduling/LoadPartitioningDistributed.h, src/runtime/distributed/worker/MPIHelper.h, src/runtime/local/context/DistributedContext.h, src/runtime/local/datastructures/AllocationDescriptorMPI.h, src/runtime/local/kernels/CreateDistributedContext.h
Abstracted duplicate code for different distributed runtime communication frameworks.
Added `distributed/coordinator/scheduling/LoadPartitioningDistributed.h` class which is used to:
- Split ranges based on some policy. For now only broadcast and simple distribution is supported.
- Sets the metadata of the matrix being distributed/broadcasted.
- Contains a static method which sets the metadata of the outputs during the computation step.
- This class can be extended in order to support more complex distribution strategies.
=> Added load partioning for distributed runtime.

CMakeLists.txt, build.sh, src/runtime/local/kernels/CMakeLists.txt, src/runtime/local/kernels/EigenCal.h, src/runtime/local/kernels/kernels.json, test/CMakeLists.txt, test/runtime/local/kernels/EigenCalTest.cpp
The EigenOp complete.
Returns two matrixes  as results, one for the Eigen Values and one for the Eigen Vectors.
The res1 matrix for eigenvalues and the res2 matrix for eigenvectors
Column k of the returned matrix res2 is an eigenvector corresponding to eigenvalue number k as returned by eigenvalues(). 
The eigenvectors are normalized to have (Euclidean) norm equal to one. 
Also includes the download and build commands for the cpp Eigen library, using the cmake tool.
=> Eigen op 391

.gitignore, containers/Readme.md, containers/build-containers.sh, containers/daphne-deps.Dockerfile, containers/daphne-dev.Dockerfile, containers/daphne.Dockerfile, containers/entrypoint-interactive.sh, containers/quickstart.sh, containers/run-docker-example.sh, doc/GettingStarted.md, src/compiler/lowering/MarkCUDAOpsPass.cpp
* reduced to two images:
- daphneeu/daphne - ready-to-run daphne precompiled with minimal deps
- daphneeu/daphne-dev - everything needed for developing DAPHNE itself
* ssh access for daphne-dev: this comes handy when using IDE extensions like VSCode Remote SSH or CLion
* CUDA 12.1
* CUDNN 8.9
* building deps from future-deps branch to already include upcoming libraries
* a few new deps like pandas (for DaphneLIB)
Closes #530
=> [DAPHNE-#530] Docker Improvements

src/runtime/local/kernels/AggAll.h, src/runtime/local/kernels/AggCol.h, src/runtime/local/kernels/AggRow.h, src/runtime/local/kernels/EwBinarySca.h, src/runtime/local/kernels/kernels.json, test/runtime/local/kernels/AggAllTest.cpp, test/runtime/local/kernels/AggColTest.cpp, test/runtime/local/kernels/AggRowTest.cpp
`AggAll.h`, `AggCol.h` and `AggRow.h` used to return the same value type as the argument. In case of some aggregations (i.e. mean, stddev) that did not make much sense for integer arguments where the result will probably be floating point value. With this PR:
- Extended these template kernels to support different return types
- Added some test cases.
Note that these kernels still support aggregation of type `DenseMatrix<int> -> int`, but we end up with losing precision (in case of `mean`). The floating-point result is **not rounded** to the closest integer, but it is **converted**. We can support rounding if we want to. But imo if the user needs that, then it makes more sense to me, to use a rounding function on the floating type result.
Closes #399.
=> [DAPHNE-#399] Aggregation kernels can return different value types

src/api/internal/daphne_internal.cpp
- For a long time, pass errors, which happen inside the DAPHNE compiler, used to be printed to std::cerr.
- Since a recent commit (4a8f003cf5b499bec4ecbb138441af8dfa2413f0), they are logged using the recently introduced logger, instead.
- Not printing the error messages to std::cerr anymore has at least two significant downsides:
- Users don't see the error messages anymore. Instead, DaphneDSL scripts may just silently fail.
- The error output captured by our script-level test cases is useless, since it is empty.
- This commit adds the printing of the error messages to std::cerr again, but also retains the logging of the errors.
=> Pass errors are not only logged, but also printed again.

src/ir/daphneir/DaphneOps.td, src/runtime/local/context/CUDAContext.cpp, src/runtime/local/context/CUDAContext.h, src/runtime/local/datastructures/DenseMatrix.cpp, src/runtime/local/datastructures/DenseMatrix.h, src/runtime/local/datastructures/Structure.h, src/runtime/local/kernels/BinaryOpCode.h, src/runtime/local/kernels/CMakeLists.txt, src/runtime/local/kernels/CUDA/AggAll.cu, src/runtime/local/kernels/CUDA/AggAll.h, src/runtime/local/kernels/CUDA/AggRow.cu, src/runtime/local/kernels/CUDA/AggRow.h, src/runtime/local/kernels/CUDA/DeviceUtils.cuh, src/runtime/local/kernels/CUDA/EwBinaryMat.cu, src/runtime/local/kernels/CUDA/EwBinaryObjSca.cu, src/runtime/local/kernels/CUDA/HostUtils.h, src/runtime/local/kernels/CUDA/Transpose.cpp, src/runtime/local/kernels/CUDA/bin_ops.cuh, src/runtime/local/kernels/Transpose.h, src/runtime/local/kernels/kernels.json
This pull request contains CUDA ops needed for the connected components algorithm (only dense versions for now).
=> Cc cuda ops

build.sh, src/runtime/local/kernels/CMakeLists.txt, src/runtime/local/vectorized/MTWrapper.h
=> [DAPHNE-#554] Use hwloc to query CPU topology

src/ir/daphneir/DaphneOps.td, src/parser/daphnedsl/DaphneDSLGrammar.g4, src/parser/daphnedsl/DaphneDSLVisitor.cpp
This change introduces some of the C++ literal suffixes that make writing single precision floats or unsigned integers way more convenient than ``x = as.f32(5.0);`` -> ``x = 5.0f;``
Yes, there should be test cases :see_no_evil:
=> [DAPHNE-#606] Some INT/FLOAT literal suffixes from C++ in DaphneDSL

src/ir/daphneir/DaphneDialect.cpp, test/api/python/scalar_ewbinary.daphne, test/api/python/scalar_ewbinary.py
_**Bug:**_
The EwLogOp implementation currently computes the element-wise logarithm of x to the base b using the `ilogb` function, which returns an integer value.
**_Solution:_**
This pull request proposes a fix to the issue by replacing the use of `ilogb` with the standard C++ logarithm function `log` to correctly compute the element-wise logarithm in floating-point. The code changes involve converting the `llvm::APFloat` values to standard double-precision floating-point numbers using the `convertToDouble` method and applying the `log` function for the correct result.
After testing the following script:
```
print(log(2.2, 3.3));
```
with the flags `--explain parsing,parsing_simplified`, i got this back:
```
IR after parsing:
module {
func.func @main() {
%0 = "daphne.constant"() {value = …
```
=> 615-Constant_folding_EwlogOp

src/compiler/inference/InferencePass.cpp
- DAPHNE support shape inference for frame type but the feature was disabled.
- The logic should be further revised as it is redundant to throw an error.
=> [MINOR] Enable shape inference for frame type

src/ir/daphneir/DaphneDialect.cpp, test/api/cli/parser/ParserTest.cpp, test/api/cli/parser/simple.daphne
While parsing a matrix object the "sparsity" and "rerpesentation" arguments can both exist. In that case trying to parse one of them while multiple exist, can make the parser emmit errors. We should consider them optional while trying to parse them in the loop.
This is currently an issue for the distributed runtime, since distributed workers emmit errors while parsing the IR sent by the coordinator. 
Example IR that a matrix contains both "sparsity" and "representation" and parsing it emits errors:
```
func.func @dist(%arg0: !daphne.Matrix<?x403394xf64:sp[2.0816421641779212E-5]:rep[sparse]>, %arg1: !daphne.Matrix<?x?xf64>, %arg2: !daphne.Matrix<?x1xf64>) -> (!daphne.Matrix<?x?xf64>, !daphne.Matrix<?x?xf64>) {
%0 = "daphne.ewMul"(%arg0, %arg1) : …
```
=> [MINOR] Parsing IR fix.

containers/README.md, doc/README.md
2 links in `containers/README.md` and `doc/README.md` had small typos.
They now redirect to the intended directories.
=> [doc] fix typo in links within Readme

src/runtime/local/vectorized/MTWrapper.h
The `get_topology` function is returning weird values since the usage of `hwloc` #563.
https://github.com/daphne-eu/daphne/blob/ccba9387a9b33e5c6b46df0aa3477d3bbab0fbfd/src/runtime/local/vectorized/MTWrapper.h#L87-L96
Namely, the function was just constructing vectors of the correct sizes, but not actually setting the information.
This PR uses `hwloc` to return the same information as before #563 and fix #650
=> #650 fix get topology

src/runtime/local/io/WriteCsv.h, test/CMakeLists.txt, test/api/cli/io/.gitignore, test/api/cli/io/WriteTest.cpp, test/api/cli/io/matrix_full_ref.csv, test/api/cli/io/matrix_view_ref.csv, test/api/cli/io/readMatrix.daphne, test/api/cli/io/writeMatrix_full.daphne, test/api/cli/io/writeMatrix_view.daphne
This PR fixes #669 for the case of `.csv` files.
Now `WriteCsv` takes the `rowSkip` argument of the matrix it's iterating over into account.
=> [DAPHNE-#669] properly handle views in `WriteCsv` kernel

doc/DaphneDSL/Builtins.md, src/runtime/local/kernels/OneHot.h, test/CMakeLists.txt, test/runtime/local/kernels/OneHotTest.cpp
This PR fixes #687 by adding a simple bound check for the `cArg` value used for the OneHot encoding. Previous asserts have been replaced with runtime errors and are tested in `OneHotTest.cpp`. The loop setting all values within an encoded segment to zero is now also a single `memset` instruction.
Onehot now also accepts `0` as an argument for `info`, which signals to omit the corresponding column instead of encoding or copying it to `res`. Currently, if all values in `info` are `0` a runtime error is thrown. This could be changed to return an empty `res` instead.
=> [DAPHNE-#687] OneHot bound check

.github/workflows/main.yml
- As a part of our CI workflows, we run the entire DAPHNE test suite.
- The tests reside in the catch2-based executable run_tests.
- Normally (e.g., in a local dev environment), we don't run run_tests directly, but invoke it indirectly through test.sh.
- test.sh offers a few arguments and sets a few environment variables such that the tests can run as expected.
- In the CI workflow, we initially executed test.sh to run the test cases.
- However, in ebfcc3bfe9457fc8106ba87c62c89ba7b2b4f48f, this was changed to invoking run_tests directly (plus adding a few essential environment variables on the command line).
- The motivation back then was that test.sh re-builds run_tests, but potentially with unwanted parameters (in the worst case, this can result in pulling the LLVM repo).
- In the …
=> [DAPHNE-#747] Use test.sh in CI again.

src/api/python/README.md, src/api/python/clean.sh, src/api/python/pyproject.toml
extending docs
naming project to daphne-lib
=> daphnelib: improve pyproject.toml and readme

mkdocs.yml
Currently, mkdocs uses `polyfill.io` to build the online Daphne documentation.
It has been reported that the site is involved in a supply chain attack delivering malicious code instead.
- https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet
- https://www.sonatype.com/blog/polyfill.io-supply-chain-attack-hits-100000-websites-all-you-need-to-know
This PR simply removes the dependency without replacement which should not impact the documentation in most browsers. If needed, e.g. Cloudflare currently provides polyfill over their cdn.
=> [security] Remove polyfill.io dependency in docs

src/runtime/local/kernels/kernels.json, test/codegen/sum_agg.mlir, test/runtime/local/kernels/AggAllTest.cpp
Closes #662 and #663
The new tests in test/runtime/local/kernels/AggAllTest.cpp confirm that the kernel implementations of the SumAll operation are working correctly for all combinations of the value types double, float, uint8_t, uint32_t, uint64_t, int8_t, int32_t, int64_t. They only need to be pre-compiled to be available to Daphne scripts.
Changes to src/compiler/lowering/AggAllOpLowering.cpp are extracted from my LDE PR #653 and enable SumAll to be called with MLIR code generation for the value types listed above.
=> Add AggAll kernels for missing value types

src/runtime/local/kernels/MatMul.cpp, test/runtime/local/kernels/MatMulTest.cpp
Fixes #700 
#700 mentions an error in the integer MatMul kernels. This PR gives the following correct result for the mentioned example:
```
DenseMatrix(3x3, int64_t)
1 0 0
0 2 0
0 0 3
DenseMatrix(3x3, int64_t)
1 0 0
0 4 0
0 0 9
DenseMatrix(3x3, int64_t)
1 0 0
0 4 0
0 0 9
DenseMatrix(3x1, int64_t)
1
2
3
```
=> Address Wrong results using Integer Matmul Kernels after Matrix resizing

src/runtime/local/io/File.h, src/runtime/local/io/MMFile.h, src/runtime/local/io/ReadCsvFile.h, src/runtime/local/io/ReadParquet.h
Daphne's getLine() calls libc's getline() with a NULL lineptr on each invocation. This results in getline() allocating a new buffer on each call, which, I think, never gets freed resulting in a memory leak.
=> Refactor getLine() to avoid potential memory leak

doc/GettingStarted.md, install-ubuntu-packages.sh
This PR aims to update the software requirements needed to compile DAPHNE without containers.
The list of required packages has been sorted alphabetically and extended with `zlib1g-dev` to satisfy a `cmake` dependency and `unzip`.
Furthermore, the existing [install-ubuntu-packages.sh](https://github.com/daphne-eu/daphne/blob/main/install-ubuntu-packages.sh) script has been updated to install `cmake` using `snap` on `Ubuntu 20.04` to fulfill the version requirement, as well as a newer version of `llvm-*-tools` on current releases. However, there are two points to consider:
- For `Ubuntu 18.04` it references the documentation ("`custom toolchain needed`") but I am not aware of any further clarification in the documentation to help setup the environment, which makes it difficult to proceed …
=> Update software requirements in doc

doc/DaphneDSL/Builtins.md, src/ir/daphneir/DaphneDialect.cpp, src/ir/daphneir/DaphneOps.td, src/parser/daphnedsl/DaphneDSLBuiltins.cpp, src/runtime/local/kernels/Sparsity.h, src/runtime/local/kernels/kernels.json
This PR introduces a new `SparsityOp` that allows users to print the compile-time sparsity estimate of a matrix to the screen. The function can be called using `sparsity(Matrix)`, which will be replaced with the sparsity value through canonicalization if the sparsity is known. If the sparsity is unknown, it will return -1.
This PR does not yet include tests. The SparsityOp functionality will be tested as part of [#766](https://github.com/daphne-eu/daphne/issues/766).
=> Implementation of new SparsityOp

src/api/python/daphne/operator/nodes/matrix.py, src/api/python/daphne/operator/nodes/scalar.py, src/parser/daphnedsl/DaphneDSLBuiltins.cpp, test/api/python/matrix_ewunary.daphne, test/api/python/matrix_ewunary.py, test/api/python/scalar_ewunary.daphne, test/api/python/scalar_ewunary.py
This code implements issue #775 .
- DaphneDSL recently supported the additive inverse operator, but DaphneLib didn't support it yet.
- Python has the __neg__ method to override the additive inverse operator
- Added script-level test cases
=> [DAPHNE-#775] Support for unary minus in DaphneLib

src/compiler/execution/DaphneIrExecutor.cpp, src/ir/daphneir/DaphneDialect.cpp, src/runtime/local/kernels/MatMul.h, src/runtime/local/kernels/kernels.json, test/runtime/local/kernels/MatMulTest.cpp
This PR implements a kernel for the matrix multiplication between two CSR matrices.
Related Issue: #793 
Fixes also #783 
- I needed to provide an estimation of the number of non-zeros elements for the resulting matrix. I had a "guess" but probably this guess can be improved (maybe: https://link.springer.com/content/pdf/10.1023/A:1009716300509.pdf)
- I am not sure if I need to add more to the `kernels.json`? like for other types than `double`
=> Implementation of CSR/CSR Matrix Multiplication (`@`)

src/api/daphnelib/DaphneLibResult.h, src/api/internal/daphne_internal.cpp, src/api/python/daphne/script_building/script.py, src/api/python/daphne/utils/daphnelib.py
[DaphneLib-#717]  handle daphne failure in daphne lib
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Summary
This PR closes issue #717 by handling execution errors in DaphneLib.
Changes:
* `error_message`: Introduced a new variable in DaphneLibResult to store execution error messages from DSL scripts.
* Error Handling in C++: Updated `src/api/internal/daphne_internal.cpp`  to capture and store execution error messages in the `error_message` variable when a DSL script fails.
* Error Handling in Python: Enhanced error handling in `src/api/python/daphne/script_building/script.py` to process and log execution error messages during DSL script execution.
=> [DAPHNE-#717]  handle daphne failure in daphne lib

src/compiler/lowering/LowerToLLVMPass.cpp, test/api/cli/controlflow/ControlFlowTest.cpp, test/api/cli/controlflow/for_manyiterations_1.daphne, test/api/cli/controlflow/for_manyiterations_2.daphne, test/api/cli/controlflow/while_manyiterations_1.daphne, test/api/cli/controlflow/while_manyiterations_2.daphne
- As described in #77, DaphneDSL loops with many iterations (e.g., >100k) crash DAPHNE.
- The reason is that LowerToLLVMPass creates LLVM::AllocaOp in several places and for various purposes.
- These AllocaOps could also be inside a loop, which means that the memory they allocate piles up until the stack is exhausted, because it is only freed at the end of the "scope" (function).
- This commit solves the problem by ensuring that all AllocaOps created in LowerToLLVMPass are inserted at the beginning of the function surrounding the currently considered operation.
- With that, there are no AllocaOps in loops anymore.
- Note that the memory allocated by the AllocaOps can safely be reused by repeated kernel calls in different loop iterations.
- Added script-level test cases employing loops …
=> [DAPHNE-#77] Avoid stack overflow in long-running DaphneDSL loops.

doc/DaphneLib/APIRef.md, src/api/python/daphne/context/daphne_context.py, test/api/python/DaphneLibTest.cpp, test/api/python/data_transfer_numpy_3.daphne, test/api/python/data_transfer_numpy_3.py
- Previously only numpy arrays with 1 or 2 dimensions were supported.
- Added support for numpy arrays with more than 2 dimensions.
- Implementation is analogous to tensorflow and pytorch with a simple reshape to a 2d numpy array.
- Added tests for ndim numpy arrays transfers.
=> [DAPHNE-#711] Added data transfer with numpy for arrays of more than 2 dimensions

src/ir/daphneir/DaphneDialect.cpp, test/api/cli/operations/CanonicalizationConstantFoldingOpTest.cpp, test/api/cli/operations/binary_op_casts_constant_folding.daphne, test/api/cli/operations/binary_op_casts_constant_folding.txt
Constant folding required the operands to have the same type. For instance, the following two DaphneDSL scripts would be perfectly amenable to constant folding, but make the DAPHNE compiler crash with the respective error messages:
`print(1 * as.si32(1));`
`daphne: /daphne/thirdparty/llvm-project/llvm/lib/Support/APInt.cpp:226: llvm::APInt llvm::APInt::operator*(const llvm::APInt &) const: Assertion BitWidth == RHS.BitWidth && "Bit widths must be the same"' failed.
...
Segmentation fault (core dumped)`
FIxed it by comparing the bit width in the `constFoldBinaryOp` method. If they are not the same, the smaller one is getting type promoted to the bigger one (reusing the `CastOp` method to perfom this type promotion).
Aded testcases for binary op of different types
=> [DAPHNE-#772] Fix Constant folding crashes for values of different types

doc/development/ImplementBuiltinKernel.md, src/runtime/local/kernels/experimental/gemv/Makefile, src/runtime/local/kernels/experimental/gemv/gemv.cpp, src/runtime/local/kernels/experimental/gemv/gemv.json
This commit introduces the `experimental/` folder for kernels. This folder will contain alternative, experimental implementations of our kernels. These experimental implementations are using the kernel catalog feature from #456.
While being experimental, the kernels are not tightly coupled to DAPHNE, e.g, they are not used per default without specifying the required kernel hint to call the kernel and they are not tested as part of our test suite or built when compiling `libAllKernels.so`. Once an experimental kernel is to be moved to our default kernels, passing all the tests is required.
Making kernels executable when running DAPHNE while not yet being part of our kernel library helps with development on improving kernels.
- Dependencies can be used while being experimental without …
=> Experimental kernels folder

.clang-format
Line length extended to accomodate for screen sizes that can't even be called modern nowadays.
=> Code formatting to 120 columns

src/ir/daphneir/DaphneInferTypesOpInterface.cpp
This patch fixes a bug in the `CastOp::inferTypes` implementation. For a matrix type of unknown value type, it resets the matrix type by calling our custom builder `MatrixType::get(ctx, valueType)` instead of using the matrix type of the result matrix and only replacing the unknown value type.
This means that for example, casts from `daphne.Matrix<?x?x!daphne.Unknown>` to
`daphne.Matrix<?x?x!daphne.Unknown:rep[sparse]>`, the matrix representation would reset and the cast is no longer casting from dense to sparse.
This fix is required for #852 #853 
Closes #861
=> [daphneir] fix CastOp::inferTypes bug (#861)

src/runtime/local/kernels/EwUnarySca.h, test/runtime/local/kernels/EwUnaryScaTest.cpp
The EwUnary kernel used the C stdlib `abs` function which instead of the appropriate C++ `std::abs` function. This caused a bug where calling `abs` with floating point values were cast to integer values during conversion.
Closes #863
=> [kernels] fix usage of C stdlib abs (#863)

src/api/cli/DaphneUserConfig.h, src/api/internal/daphne_internal.cpp, src/parser/config/ConfigParser.h, src/runtime/local/vectorized/LoadPartitioning.h, src/runtime/local/vectorized/LoadPartitioningDefs.h, src/runtime/local/vectorized/MTWrapper.h, src/runtime/local/vectorized/MTWrapper_dense.cpp, src/runtime/local/vectorized/MTWrapper_sparse.cpp, src/runtime/local/vectorized/WorkerCPU.h, test/runtime/local/vectorized/MultiThreadedKernelTest.cpp
Refactors the code using the scheduling options in the
vectorized pipeline to the enum class types instead of hard-coded
integers.
With that, usage and readability of the concerning code is considerably improved.
- stronger type safety
- prevents accidental comparisons with integer or other enum types
- no implicit conversion to integers
=> [#731] refactor scheduling options to enum class

src/runtime/local/vectorized/LoadPartitioning.h
This patch adds MSTATIC to the switch case in the LoadPartitioning. Before, this was implicitly handled by the default case.
Closes #892
=> [#892] explicitly use MSTATIC in LoadPartitioning

src/compiler/lowering/EwOpsLowering.cpp
This PR changes the existing ewBinaryOp codegen to broadcast `rhs` if possible.
So far, the ewBinary codegen only accepted scalars, matrices of equal shape or combinations of `lhs` being a matrix and `rhs` being either a scalar or singleton.
Now `rhs` can also be given as a matching (equal to `lhs` in one dimension and size `1` in the other) row or column vector.
An example script (--explain mlir_codegen is optional to show the generated IR):
```
// RUN: ./bin/daphne --select-matrix-repr --mlir-codegen --explain mlir_codegen ./fileName.daphne
lhsMat = [1, 2, 3, 4, 5, 6](2,);
rhsMat = [10, 20, 30, 40, 50, 60](2,);
rhsRowMat = [10, 20, 30](1,);
rhsColMat = [10, 20](,1);
rhsScalar = 10;
rhsSingleton = [10];
print(lhsMat + rhsMat);
print(lhsMat + rhsRowMat);
print(lhsMat + rhsColMat); …
```
=> Broadcasting for ewBinary codegen

src/compiler/lowering/SparsityExploitationPass.cpp, test/CMakeLists.txt, test/api/cli/codegen/SparsityExploitTest.cpp, test/api/cli/codegen/sparsityExploit.daphne, test/codegen/sparseExploit.mlir
This PR adds some tests and makes some minor changes to the sparsity exploit lowering pass `src/compiler/lowering/SparsityExploitationPass.cpp` and is complementary to #919. For clarification, the currently fixed operations for the `SparsityExploitationPass` implement a cross-entropy computation of a sparse `CSRMatrix` and a `DenseMatrix`
**Changes:**
- added script level and filecheck tests
- replaced `Operation *` type with cast to specific Operation (`auto op = parentOp.getDefiningOp<daphne::OpName>()`)
- allows to make use of specific `get` functions for better readability (e.g. `.getLhs()`, `.getTransa()`)
- replaced `notifyMatchFailure` with `ErrorHandler::compilerError`
---
_Complementing the original PR's description:_
The `lower-sparse-exploit` pass is part of the `mlir-codegen` …
=> Adding tests for sparse exploit codegen

src/api/cli/DaphneUserConfig.h, src/api/internal/daphne_internal.cpp, src/compiler/lowering/LowerToLLVMPass.cpp, src/compiler/lowering/RewriteToCallKernelOpPass.cpp, src/runtime/local/instrumentation/KernelInstrumentation.cpp, src/runtime/local/kernels/genKernelInst.py, src/util/KernelDispatchMapping.cpp, src/util/KernelDispatchMapping.h, src/util/Statistics.cpp
This patch adds tracking for `_vectN` functions generated when using
--vec and displays them in the output of `--statistics`.
Also contains a small commit with minor changes so it's run as part of the CI test run.
=> feat: track `_vectN` functions in `--statistics`

src/api/python/daphne/context/daphne_context.py, src/ir/daphneir/DaphneOps.td, src/parser/daphnedsl/DaphneDSLBuiltins.cpp, src/runtime/local/kernels/ReceiveFromNumpy.h, src/runtime/local/kernels/kernels.json
This pull request fuses the unsigned 32-bit integers `upper` and `lower` arguments in the `ReceiveFromNumpy` operation into one unsigned 64-bit integer called `address`. The issue linked to this pull request is: https://github.com/daphne-eu/daphne/issues/710
=> Unified upper and lower part of address argument in `ReceiveFromNumpyOp`

src/compiler/lowering/RewriteToCallKernelOpPass.cpp, src/runtime/local/kernels/genKernelInst.py
Kernel instrumentation currently causes a use after free bug in  `destroyDaphneContext`.
After instrumentation, `_destroyDaphneContext` looks like this:
```c++
preKernelInstrumentation(kId, ctx);
destroyDaphneContext(ctx);
postKernelInstrumentation(kId, ctx); // <- use after free in here
```
This PR fixes this by disabling instrumentation for destroyDaphneContext.
As [`RewriteToCallKernelOpPass`](https://github.com/daphne-eu/daphne/blob/aa1fb14badc0083c2d927210b782745544260f38/src/compiler/lowering/RewriteToCallKernelOpPass.cpp#L489) assumes that the `kId` and `ctx` parameters are present for all kernels besides `createDaphneContext`, this parameter is retained in `destroyDaphneContext` to keep it simple.
=> fix use after free by removing instrumentation from `destroyDaphneContext`

.gitmodules
This is a first approach to a Daphne UI. It consists of two sub-projects, an API written in python (Flask) and a frontend web ui implemented with Angular. You can read more about how to use or extend the UI in the README files. 
The UI contains a main panel used for executing Daphne and an additional "Experiments" tab which contains a few examples that were demonstrated during EuroPar2023 workshop. Users can select to run a Daphne script from the UI, the available scripts displayed can be configured through `src/tools/web-ui/backend/config.json` (read more `backend/README.md`).
**One major thing missing** is testing (both the API and the Angular app), however I believe we can merge it for now and work on this later if we decide to extend it.
I am opening this as a pull request to open a …
=> Daphne web UI

.gitignore, src/api/python/daphne/utils/consts.py
- Currently, DaphneLib stores all its temporary files (generated DaphneDSL script as well as data that is transfered from Python to DAPHNE via files) in the directory "/tmp/DaphneLib/".
- On systems used by multiple users, this directory is typically owned and only writable by the user who creates it.
- If another user uses DaphneLib afterwards (e.g., by running the test suite), they encounter file permission errors that make DaphneLib crash and the test cases fail.
- The reason why the temporary files are stored in a central place (not inside the DAPHNE source code tree) is that the source tree may not be available or writable when DAPHNE was installed as a Python package (see 25f2a3c1f34ca4e2068deb06fae01d4188b8392e for details).
- This commit fixes the problem, while keeping the …
=> [DAPHNE-#785] Fix DaphneLib file permission error on multi-user systems.
